### PR TITLE
Fix UnicodeDecodeError on Windows

### PR DESCRIPTION
**Pull request by BastianZim**
Hi,

I'm currently in the process of adding `quantumflow` to conda-forge and stumbled upon the following error when running the tests:

```shell
================================== FAILURES ===================================
_______________________________ test_copyright ________________________________

    def test_copyright() -> None:
        """Check that source code files contain a copyright line"""
        exclude = set(["quantumflow/version.py"])
        for fname in glob.glob("quantumflow/**/*.py", recursive=True):
            if fname in exclude:
                continue
            print("Checking " + fname + " for copyright header...  ", end="")
    
            with open(fname) as f:
>               for line in f.readlines():

quantumflow\config_test.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <encodings.cp1252.IncrementalDecoder object at 0x000002A23D3F1930>
input = b'# Copyright 2020-, Gavin E. Crooks and contributors\n#\n# This source code is licensed under the Apache License, Ver..., vers in versions.items():\n        print(name.ljust(name_width), vers, file=file)\n    print(file=file)\n\n\n# fin\n'
final = False

    def decode(self, input, final=False):
>       return codecs.charmap_decode(input,self.errors,decoding_table)[0]
E       UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1001: character maps to <undefined>

..\_test_env\lib\encodings\cp1252.py:23: UnicodeDecodeError
```

Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=419963&view=logs&jobId=240f1fee-52bc-5498-a14a-8361bde76ba0&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=06d62fd2-ab49-5add-9ee5-83b6882d7d2b

I believe this is due to a missing encoding definition but cannot verify it, as don't have a windows machine, which is why I added the full OS suite here. Once verified, I can remove it again, if required. 

It is tested using a patch though, with the logs and PR here: https://github.com/conda-forge/staged-recipes/pull/17115

### CODE REVIEW

**Comment by gecrooks** [comment]
I don't have a windows box either, so the code has not been tested on windows. Looks like the way I'm testing the examples is failing on windows also.

**Comment by BastianZim** [comment]
I think the failures on windows are unrelated, as everything works on my side.
Before I complicate this further, should be easier if I just add the patch downstream and close this PR again, what do you think?

**Comment by gecrooks** [comment]
Most of the builds are failing because black is unhappy (Change single quotes to double quotes). But the window's builds are failing when they run `examples\examples_test.py`. (That test doesn't live in the main quantumflow code directory, so maybe its getting skipped on your end?)

**Comment by BastianZim** [comment]
> black is unhappy

Fixed

> That test doesn't live in the main quantumflow code directory, so maybe its getting skipped on your end?

Ahh yes, that's it. I'm only running what's under the main dir. I think it comes from the `subprocess.call()` part which should be fixable with using `sys.executable` explicitly. `shell=True` could also be used. Which one do you prefer?

---

The failures on macOS are due to ` sudo apt-get` from what I can see. Should we ignore that and take mac-os out again or do you want to substitute it with brew? (If the deps are available there haven't checked yet)

Edit: Checked and not everything is there. If you want to keep the tests on all os, I would only run pytest on all of the os and run the rest only on linux.

**Comment by gecrooks** [comment]
You can take the macos test out for now. I like the idea, so I'll fix it up latter. (I code on mac, so nothings likely to be actually broken on a mac build)

**Comment by BastianZim** [comment]
Will do

> I code on mac, so nothings likely to be actually broken on a mac build

Me too which is why I'm more trial-and-erroring my way through windows, sorry about the excessive use of build time. 😄

**Comment by BastianZim** [comment]
For windows, we probably need to fix the directory as "/" is only used on UNIX.

**Comment by BastianZim** [comment]
I had to take out the `requirements.txt` step as that fails on windows. If this is needed, I'd write a separate script for that.

Otherwise, this should be good to go. Before merging, I would create a separate PR though to have a cleaner commit history.

**Review by gecrooks — APPROVED** [review]

**Pull request merged**
