### PR TITLE
Fix examples

### LINKED ISSUE #88: Examples directory is installed as a separate package
Currently, the examples directory is installed as a separate package:

```zsh
(base) user@iMac site-packages % ls
PIL
Pillow-8.4.0.dist-info
README.txt
__pycache__
_distutils_hack
cycler-0.11.0.dist-info
cycler.py
dateutil
decorator-4.4.2.dist-info
decorator.py
distutils-precedence.pth
examples
fontTools
fonttools-4.28.2.dist-info
isympy.py
kiwisolver-1.3.2.dist-info
kiwisolver.cpython-310-darwin.so
matplotlib
matplotlib-3.5.0-py3.10-nspkg.pth
matplotlib-3.5.0.dist-info
mpl_toolkits
mpmath
mpmath-1.2.1.dist-info
networkx
networkx-2.6.3.dist-info
numpy
numpy-1.21.4.dist-info
opt_einsum
opt_einsum-3.3.0.dist-info
packaging
packaging-21.3.dist-info
pip
pip-21.3.1-py3.9.egg-info
pkg_resources
pylab.py
pyparsing
pyparsing-3.0.6.dist-info
python_dateutil-2.8.2.dist-info
quantumflow
quantumflow-1.2.1.dev10+g579ce88.dist-info
scipy
scipy-1.7.3.dist-info
setuptools
setuptools-59.4.0-py3.10.egg-info
setuptools_scm
setuptools_scm-6.3.2.dist-info
six-1.16.0.dist-info
six.py
stdgates
sympy
sympy-1.9.dist-info
tomli
tomli-1.2.2.dist-info
translate
wheel
wheel-0.37.0-py3.9.egg-info
```

This should not happen as it's not really a package. I tried to fix that in https://github.com/gecrooks/quantumflow-dev/pull/87 but it's not working so far. To be honest, my experience with `.cfg` is also limited which is why I opened this issue instead of fixing it.

### PR DESCRIPTION
**Pull request by BastianZim**
Currently, _examples_ is installed as a separate package as it doesn't live under the src dir. This PR should exclude it.

Note: This is guesswork though because I'm not sure why it's even included in the first place.

Closes #88

### CODE REVIEW

**Comment by gecrooks** [comment]
Try adding the examples/__init__.py  file back in. That tells python that the directory is a module and I think its needed for pytest to run the examples unit test.

**Comment by gecrooks** [comment]
Well that didn't work. Let me have a poke at this...

**Comment by BastianZim** [comment]
It's a strange thing, to be honest. Theoretically, it should just be removable and the only change should be that it doesn't get installed in the end. But because of bugs like https://github.com/pypa/setuptools/issues/2688 I'm not sure what the best approach is.

**Comment by gecrooks** [comment]
I believe I've fixed this problem in master.

**Comment by BastianZim** [comment]
Thank you! Would you mind creating a new release for this?

**Pull request closed without merging**
